### ISSUE TITLE
espanso unable to start service: timed out - Ubuntu 20.04/X11

### ISSUE THREAD

**Issue by bayronbarquero** [espanso/espanso#1290]
Legacy version stopped working, even thought espanso start didn't show any error, espanso status showed it wasn't running.
Then I updated to v2.1.6-beta but after installation I'm getting this error:
``` $ ps -ef | grep espanso
roco+    5726    4937  0 20:09 pts/1    00:00:00 grep --color=auto espanso
20:09 | ~
 $ espanso start --unmanaged
unable to start service: timed out
Hint: sometimes this happens because another Espanso process is left running for some reason.
      Please try running 'espanso restart' or manually killing all Espanso processes, then try again.
```
I've tried deleting everything espanso related and reinstalling but getting the same error. Ran this after reading comments leading to pull #1281
``` $ espanso -vv worker
20:05:14 [worker(4955)] [DEBUG] (1) espanso_path: detected config directory in $HOME/.config/espanso
20:05:14 [worker(4955)] [DEBUG] (1) espanso_path: detected default runtime dir: "/home/bacalderon/.cache/espanso"
20:05:14 [worker(4955)] [DEBUG] (1) espanso_path: detected default packages dir: "/home/bacalderon/.config/espanso/match/packages"
20:05:14 [worker(4955)] [INFO] reading configs from: "/home/bacalderon/.config/espanso"
20:05:14 [worker(4955)] [INFO] reading packages from: "/home/bacalderon/.config/espanso/match/packages"
20:05:14 [worker(4955)] [INFO] using runtime dir: "/home/bacalderon/.cache/espanso"
20:05:14 [worker(4955)] [INFO] system info: Ubuntu v20.04 - kernel: 5.14.0-1044-oem
20:05:14 [worker(4955)] [DEBUG] (1) espanso_config::config::store: loaded default config at path: "/home/bacalderon/.config/espanso/config/default.yml"
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'alacritty_terminal_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'emacs_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'gedit_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'generic_terminal_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'kitty_terminal_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'konsole_terminal_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'libreoffice_writer_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'simple_terminal_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'simple_terminal_2_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'terminator_terminal_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'termite_terminal_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'thunderbird_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'tilix_terminal_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'urxvt_terminal_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'xterm_terminal_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'yakuake_terminal_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::patch::config_store: enabled 'virtualbox_x11' patch
20:05:14 [worker(4955)] [DEBUG] (1) espanso::cli::worker: starting with start-reason = None
20:05:14 [worker(4955)] [DEBUG] (1) espanso::icon: skipping extraction for '"/home/bacalderon/.cache/espanso/iconv2.png"', as it's already present
20:05:14 [worker(4955)] [DEBUG] (1) espanso::icon: skipping extraction for '"/home/bacalderon/.cache/espanso/search.png"', as it's already present
20:05:14 [worker(4955)] [DEBUG] (1) espanso::icon: skipping extraction for '"/home/bacalderon/.cache/espanso/icon_no_background.png"', as it's already present
20:05:14 [worker(4955)] [INFO] binded to IPC unix socket: /home/bacalderon/.cache/espanso/espansoworkerv2.sock
20:05:14 [worker(4955)] [INFO] using X11AppInfoProvider
20:05:14 [worker(4955)] [INFO] using X11Source
20:05:14 [worker(4955)] [ERROR] X11Source destruction cannot be performed, handle is null
20:05:14 [worker(4955)] [ERROR] thread 'engine thread' panicked at 'failed to initialize detector module: detection source initialization failed': espanso/src/cli/worker/engine/mod.rs:139
20:05:14 [worker(4955)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
20:05:14 [worker(4955)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160```

**Comment by lobau** [comment]
Same issue on Fedora 36

**Comment by nonsonoalessio** [comment]
@lobau You may want to try this (by default, sessions in Fedora 36 happens to be Wayland sessions and not X11 sessions):
1. First launch `setxkbmap - query`. The output will be something like:
```
rules:      evdev
model:      pc105
layout:     us
```
Copy all this. 
2. Go to your espanso's config folder (which should be `~/.config/espanso/config/`) and look for `default.yml` file. 
3. You may want to open this file and paste into it the output of the command above, bearing in mind you have to indent the output. The file now should look like this:
```
# Some comments
keyboard_layout:
  <output of the copied command>
```

[Credit 1](https://github.com/espanso/espanso/issues/901).
[Credit 2](https://github.com/espanso/espanso/issues/921).

Unfortunately, I'm afraid this will not be useful for _bayronbarquero_, I'm sorry.

**Comment by lobau** [comment]
It seemed to have been an issue with Wayland. I switched back to xorg and espanso launched without issues.

**Comment by ewoks** [comment]
@lobau @nonsonoalessio not nice to hijack the thread like this :/  
in log is visible it is X11 not Wayland...

@bayronbarquero did this got resolved with some newer version?

**Comment by bayronbarquero** [comment]
I updated to Ubuntu 22.04 and got the latest espanso running, so not sure it issue still there. For now I'll close this issue, thanks for the follow up @ewoks
