### ISSUE TITLE
Autohotkey

### ISSUE THREAD

**Issue by AhmedThahir** [espanso/espanso#1488]
**Describe the bug**
Espanso does not expand when I use my custom keyboard layout script, but works when I disable my script.

**To Reproduce**
1. Use [Colemak autohotkey](https://github.com/omigo/colemak/blob/master/qwerty-to-colemak.ahk) script to use another keyboard layout.
2. Use espanso as usual
3. Typing `:date` using my keyboard layout does not expand to the current date

**Expected behavior**
I expect espanso to work the same as if I do not use my script

**Setup information**
- OS: Windows 10
- Version: 2.1.8

**Comment by ernstki** [comment]
@AhmedThahir Federico will undoubtedly have deeper insights here, but try `:sagf` (`:date`, but using the keys from the Colemak layout) and see if you get a different result.

My gut feeling is that it would be very hard indeed for Federico to support your use case, especially if AutoHotkey and Espanso are working with the keyboard input buffer different levels. The AutoHotkey script is essentially waiting for certain key codes from the hardware and then inserting different characters into the input buffer. Espanso is probably receiving those same key codes, that is, the ones from the underlying QWERTY layout.

The result might be different if you were to use the "official" Colemak layout for Windows. Although I can't vouch for it, the Wikipedia article for Colemak [mentions](https://en.wikipedia.org/wiki/Colemak#cite_note-2) that there's one available for download from colemak.com. You'll need to decide for yourself whether installing third-party software that is literally monitoring every keystroke is something you're comfortable with. `;)`

**Comment by jtroo** [comment]
Espanso ignores all events sent as a result of software using `SendInput`, e.g. when using:

- AutoHotkey
- PowerToys Keyboard Manager
- KMonad
- Kanata (my project)

The code responsible for that is here:

https://github.com/espanso/espanso/blob/4caf7f644267aa88b30939b3ced7fd94a8b92672/espanso-detect/src/win32/mod.rs#L188

There is a configuration option to stop ignoring these events, but then espanso just doesn't work correctly, from what I've found:

```yaml
# The default is true
win32_exclude_orphan_events: false
```

I've tried `backend: Clipboard` and `backend: Inject` and neither work correctly for me - the text expansion appears but then gets erased afterwards, with some extra leftover characters. E.g. when I type `gst` which expands to `git status`, I get see on screen:

- `gst`
- `git status`
- `ggst` - this is the final state

Seems like espanso could be a bit smarter about when it ignores SendInput events. Even with the configuration set to false, it could choose to still ignore events when espanso itself is trying to do a text expansion.

**Comment by Geobert** [comment]
Any change to do an upstream PR of that? It will also fix https://github.com/espanso/espanso/issues/1582

**Comment by jtroo** [comment]
> Any change to do an upstream PR of that? It will also fix #1582

There was a PR but the maintainer did not like the approach. I don't have a desire to keep pushing on getting this change in, but anyone is welcome to take the code and try their own PR inspired from it.

https://github.com/espanso/espanso/pull/1531

**Comment by AucaCoyan** [comment]
Sad that it couldn't be landed, I thank you for all the effort and good will!
I hope we can achieve it soon-ish 😄

**Comment by rpnfan** [comment]
A fix is needed for that indeed. The workaround jtroo implemented does help. Either it should be integrated or another solution found! :)

**Comment by AucaCoyan** [comment]
We would love to, but we are short of hands. Do you have time and willpower to take this one @rpnfan ?

**Comment by rpnfan** [comment]
I can do testing, but am not a programmer. So sorry, can not help here to fix that. Jtroo already submitted a patch that espanso will work with Kanata. The patch was not accepted if I understand that correct. Why not accept the patch, even if it would be "only" a workaround? I do not know if that is the case, but even in that case a working solution is better than none IMO. Kanata gains more and more momentum and espanso is the perfect companion for Kanata. So I think that is great, when the two programs can work hand in hand and not kill each others function.

**Comment by AucaCoyan** [comment]
It requires a solution a bit more complex that it is on the PR #1531 Not that is bad as it is now, but we need to be careful on what do we merge, as many bugs can come with it. We don't know how many things can break a recursive trigger, and we don't want to take the risk for the users.
It's on the bucket list, but on the present nobody can take it

**Comment by eugenesvk** [comment]
> We don't know how many things can break a recursive trigger, and we don't want to take the risk for the users.

This risk can be avoided by making the fix optional, disabled by default. And this will also help answer which things break as there will be people testing it

**Comment by jtroo** [comment]
Seems this ticket is gaining attention again, so let me describe what my PR does in relation to the default Espanso behaviour.

- In Espanso's default configuration, `(*_self).exclude_orphan_events` is `true`, meaning all synthetic events are ignored
- In Espanso's code today, with `(*_self).exclude_orphan_events` set to `false` (not the default), Espanso **is already completely broken**
- With the PR, in the default configuration of Espanso, this code only updates an atomic counter. Nothing else. All ignored events continue to be ignored. Exact same behaviour.
- With the PR, with `(*_self).exclude_orphan_events` set to `false`, the new code will ignore extra events based on the counter, where before all synthetic events were passed through. Meaning it is strictly improved in the scenario of "risky recursive triggers"
- The code only runs on Windows, so does not impact other platforms

**Comment by rpnfan** [comment]
The suggestion from Eugene seems sensible to me, isn't it?

**Comment by jtroo** [comment]
The fix already has no observable effect in the default operation of Espanso. The fix only has an internal effect of incrementing and decrementing a counter. Making it configurable would only complicate the solution more.

It is unfortunate for users that use SendInput-using software that this still hasn't been merged 1.5 years after a solution has already been written. Let me state the problem, solution, and risk one more time to see if this can finally be fixed.

# Problem

By default, Espanso ignores all events originating from the SendInput Windows API. This includes its own events such as <kbd>Backspace</kbd> and <kbd>Enter</kbd>. The intent is to avoid Espanso outputs being read by the input code and interfering with expected operation, e.g. recursively triggering expansions that itself contains expandable text.

There is an existing Espanso setting to turn this ignore-behaviour off: `win32_exclude_orphan_events`. This setting is `true` by default. Setting it to `false` completely breaks Espanso on Windows and this configuration should not be used today. Why would someone want to try setting it to `false` though? Because other software uses SendInput and we want Espanso to still work properly while running such software. Today Espanso cannot do this.

# Solution

Setting `win32_exclude_orphan_events: false` breaks Espanso because Espanso begins reading its own events. The solution is to make Espanso ignore its own events even while having the setting applied. Hopefully this high level idea is straightforward.

The solution is accomplished by keeping track of expansion being in progress. In the output code, when Espanso triggers an expansion, a counter is increased by the number of output events (including presses and releases). In the input code, Espanso will decrement the counter when applicable events are seen. While the counter is greater than zero, SendInput-originating events are ignored.

Getting even more into the weeds, only a subset of Espanso's output events will be read by itself. On Windows there are two output code paths: `send_keys` and `send_text`. The `send_text` path outputs events with the unicode flag set and it turns out that these events are never seen by Espanso's input-reading code. Thus, only the `send_keys` output path needs to increment the counter. From what I recall this code path only ever sends <kbd>Backspace</kbd> and <kbd>Enter</kbd>, which is why only these events are checked for in the code.

# Risk

There is, to my judgment, **zero** risk to breaking the default Espanso functionality, because all SendInput-originating events are already being ignored. There is a minor performance cost added due to atomic integer operations which I expect to be unmeasurable in comparison to the cost of Windows API calls and other Espanso code.

The risk if the solution does not work, is that setting `win32_exclude_orphan_events: false` (not the default value) will continue to be broken. Again, zero risk because this option is already **completely broken** anyway.

---

Anyone is welcome to take my code, which worked as-is when I tested over a year ago, and open a new PR. I no longer use Espanso myself so I won't be driving the fix.

**Comment by rpnfan** [comment]
Thanks for the detailed explanation jtroo! I hope that this will be clear and the patch will be included in the main branch now!

Slightly OT @jtroo : when you do not use espanso any longer yourself -- what do you use instead?

**Comment by AhmedThahir** [comment]
Yes, even I'm curious 

> Thanks for the detailed explanation jtroo! I hope that this will be clear and the patch will be included in the main branch now!
> 
> Slightly OT @jtroo : when you do not use espanso any longer yourself -- what do you use instead?

**Comment by AucaCoyan** [comment]
Thanks jtroo for explaining so clearly the problem!. I'm currently inclined to reopen the original PR and make the steps to merge it, as it is the best scenario we have today.
I still need some more time to understand what is happening with win32_exclude_orphan_events: false, and learn more rust as this PR is above my technical comprehension.
Hang on a little bit more guys, I'm working on it!

**Comment by Comprehensive-Jason** [comment]
Is this still being actively worked on? I would love for this to be fixed. It would make Espanso integrate seamlessly with custom keyboard software like Kanata and AHK.

**Comment by AucaCoyan** [comment]
Hey all!
I did PR #2291 would you mind trying it out and see what happens? 🙏🏼 
Thanks!
@AhmedThahir @ernstki @rpnfan @Comprehensive-Jason

**Comment by Comprehensive-Jason** [comment]
@AucaCoyan Could you compile a `.exe` release so I could test it? I couldn't find any instructions for how to compile it. I tried forking the repo, merging this PR, and running the `Create release draft` action, but that didn't work either.

**Comment by AucaCoyan** [comment]
Yup! I compiled the PR in the commit 85239a2 and here you have a portable zip file 👌

[Espanso-Win-Portable-x86_64.zip](https://github.com/user-attachments/files/19727180/Espanso-Win-Portable-x86_64.zip)

**Comment by rpnfan** [comment]
Thanks, I tried the portable version: extracted it to a folder, started it, copied my yml file to the match folder. It works with the shortcut Alt-Space to launch and show me the options. But the defined shortcuts do not trigger without the search bar. When I disable kanata_gui (which uses LLHOOK), the shortcuts do trigger correct. So the patch does not seem to work, while the old kanata version jtroo compiled with that patch is working fine.

**Comment by AucaCoyan** [comment]
Just in case, did you changed the setting `exclude_orphan_events` to `false`?
[like this](https://github.com/espanso/espanso/issues/1488#issuecomment-2333305947)

**Comment by rpnfan** [comment]
No, I was not aware that I need to configure something. I outlined all steps I made.

I just tested to add

`(*_self).exclude_orphan_events: false `

to the default.yml file in the config folder. That does not help. I then tried

`exclude_orphan_events: false `

also without success. Where/ how would I need to make the configuration to make it work? 

EDIT: I just thought I can look in the jtroo version what is there in the config. The following is defined there.

`win32_exclude_orphan_events: false`

With that your patched version works! :-) I will now continue to use your patched version and report if I find any problems. The first look is fine so far!

Thanks a lot for your efforts!

**Comment by AucaCoyan** [comment]
Oh, I missed the name of the config key! 
Thank you for testing!

**Comment by rpnfan** [comment]
> The fix already has no observable effect in the default operation of Espanso.

Thanks a lot jtroo for both the patch itself and explaining in detail why it is needed and will work. 

Happy that the PR is now merged and many can continue to use Kanata, Autohotkey and so on, but still use the latest Espanso release as well! :-)

**Comment by Comprehensive-Jason** [comment]
I tried the portable version with the changes rpfan made and everything works perfectly. Can't wait for the next release with this PR!

**Comment by rpnfan** [comment]
> I tried the portable version with the changes rpfan made and everything works perfectly. Can't wait for the next release with this PR!

Yep, also looking forward to the next release -- which I fear will be in a year or so (looking at the release cycles so far...)

**Comment by pyxelr** [comment]
Hey, I just stepped on this issue, as I am using PowerToys keyboard manager to remap `\` (next to left shift) to ``` ` ```, but then my triggers do not expand with this key.

Should this be fixed now in espanso 2.3.0, or will it be fixed in the next release?

**Comment by rpnfan** [comment]
The current 2.3 does fix that tools like Autohotkey or Kanata which use LLHOOK work at all with Espanso.

Add the following to your Espanso config:

```
# following command needed for proper functioning of espanso on Windows, when used together with LLHK using programs like AutoHotkey or Kanata
win32_exclude_orphan_events: false
```
What the 2.3.0 version does not fix is that some triggers are not recognized. For example when I the unicode function of Kanata, all the chars defined in that way do not trigger Espanso. I am not sure about PowerToys, but it seems to handle shortcuts differently in the process when defining those than compared to when using these (see: https://rpnfan.github.io/keyboard-heaven/deep-dive/windows-keyboard-chain-advanced/ ). I assume something related is the cause with your redefinition in PowerToys. Maybe someone else can chime in or that information can help you to do more targeted testing to find the root cause. 

You likely need to create a new ticket, as this is not directly related to this closed one AFAIU.

**Comment by pyxelr** [comment]
@rpnfan: Thanks, I think we may need another ticket as this does not fix my problem:

```yaml
matches:
  - trigger: ";` "
    replace: "```"
    win32_exclude_orphan_events: false
```

**Comment by rpnfan** [comment]
The option I posted goes into your config file, not the match file. Something like:

.... \espanso-portable\.espanso\config\default.yml

**Comment by pyxelr** [comment]
Ah, right. It works now!

**Comment by ppreshant** [comment]
I use a different LLHK software on windows called `keymapper` and have an issue with partial completions of the espanso expansions. I just live with it so far and have disabled keymapper now since I wasn't sure if it is an easy fix so I just want to leave this comment here and notes to reproduce/ unless you want me to make a new issue!

## Details
**Espanso side**
I use this expansion which usually works unless my time involves an 8!
- so 8:56 PM becomes: 56 PM (_AND MY CAPS LOCK TURNS ON!)
- 9:38 PM becomes 9:3DPM
- 28/Apr/26 becomes 2vApr/26 (_this is a separate expansion with `vars`: `name = mydate, type = date`
```yml
  - triggers: [":now", ";;"]
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
            format: "%-I:%M %p" # format time as 3:35 pm
```
**keymapper side**: I get the issue only when these are activated/uncommented in the `keymapper.conf`
```sh
# map Home and End keys to the left side
Alt A >> Home
Alt S >> End
```
### Tried the fixes above without success
- I updated the espanso to `2.3.0` and 
- added the `win32_exclude_orphan_events: false` to my `config/default.yml`

PS: Thanks for all the work and this informative thread y'all! _espanso gives me a good way to procastinate from my work_ 😉
